apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
  name: mariadb-data
  namespace: otobo-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: nfs-client
