apiVersion: v1
kind: Service
metadata:
  labels:
    app: web
  name: web
  namespace: otobo-system
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 5000
  selector:
    app: web
  type: NodePort
